config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :parkings, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'

    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'

  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable

  validates :fullname, presence: true, length: {maximum: 50}

  has_many :parkings
  has_many :reservations
  has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
  has_many :host_reviews, class_name: "HostReview", foreign_key: "host_id"
  has_many :notifications

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else

      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

        user.skip_confirmation!
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @parkings = @user.parkings

    #shows all the guest reviews if the user is a host
    @guest_reviews = Review.where(type: "GuestReview", host_id: @user.id)

    #shows all the host reviews if the user is a guest
    @host_reviews = Review.where(type: "HostReview", guest_id: @user.id)
  end
end

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="center">
      <%= image_tag avatar_url(@user), class: "avatar-full" %>
      <% if current_user && current_user != @user %>
      <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post, class: "btn btn-default" %>
      <% end %>
    </div>
    <br/>
    <div class="panel panel-default">
      <div class="panel-heading">Verification</div>
      <div class="panel-body">
        <ul class="sidebar-list">
          <% if @user.confirmation_token %>
            <li>Email Address<span class="pull-right icon-babu"><i class="fa fa-check-circle-o"></i></span></li>
          <% end %>
          <% if @user.provider %>
            <li>Facebook<span class="pull-right icon-babu"><i class="fa fa-check-circle-o"></i></span></li>
          <% end %>
          <li>Phone Number<span class="pull-right icon-babu"><i class="fa fa-check-circle-o"></i></span></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>

    <div class="description row-space-3">
      <%= @user.description %>
    </div>

<h4>Listings (<%= @parkings.length %>)</h4><br/>

<div class="row">
  <%= render partial: "parkings/parkings_list", locals: {parkings: @parkings} %>
</div>
<br/>

<h4>Reviews From Guests (<%= @guest_reviews.count %>)</h4>
  <div class="row">
    <%= render "reviews/guest_list" %>
  </div>
  <br/>

  <h4>Reviews From Hosts (<%= @host_reviews.count %>)</h4>
  <div class="row">
    <%= render "reviews/host_list" %>
  </div>

</div>
</div>