config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :parkings, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'

    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'

  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :parking


  private

  def created_notifcation
    type = self.room.Instant? ? "New Booking" : "New Request"
    guest = User.find(self.user_id)

    Notification.create(content: "#{type} from #{guest.fullname}", user_id: self.room.user_id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    parking = Parking.find(params[:parking_id])

    if current_user == parking.user
      flash[:alert] = "You cannot book your own property!"
    else
      start_at = Date.parse(reservation_params[:start_at])
      end_at = Date.parse(reservation_params[:end_at])
      days = (end_at - start_at).to_i + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.parking = parking
      @reservation.price = parking.price
      @reservation.total = parking.price * days
      @reservation.save

      flash[:notice] = "Booked Successfully!"
    end
    redirect_to parking
  end

  def your_trips
    @trips = current_user.reservations.order(start_at: :asc)
  end

  def your_reservations
    @parkings = current_user.parkings
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_at, :end_at)
    end
end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span><i class="fa fa-bolt" style="color: #ffb400"></i> $<%= @parking.price %></span>
    <span class="pull-right">Per Day</span>
  </div>
  <div class="panel-body">
    <%= form_for([@parking, @parking.reservations.new]) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>Check In</label>
          <%= f.text_field :start_at, readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>Check Out</label>
          <%= f.text_field :end_at, readonly: true, placeholder: "End Date", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Price</td>
              <td class="text-right">$<%= @parking.price %></td>
            </tr>
            <tr>
              <td>Days(s)</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">$<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>

      <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
    <% end %>
  </div>
</div>


<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_parking_path(@parking) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_at); d <= new Date(arrValue.end_at); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_at').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_at').datepicker("option", "minDate", selected);
            $('#reservation_end_at').attr("disabled", false);

            var start_at = $('#reservation_start_at').datepicker('getDate');
            var end_at = $('#reservation_end_at').datepicker('getDate');
            var nights = (end_at - start_at)/1000/60/60/24 + 1;

            var input = {
              'start_at': start_at,
              'end_at': end_at
            }

            $.ajax({
              url: '<%= preview_parking_path(@parking) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @parking.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });

          }
        });

        $('#reservation_end_at').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_at').datepicker("option", "maxDate", selected);

            var start_at = $('#reservation_start_at').datepicker('getDate');
            var end_at = $('#reservation_end_at').datepicker('getDate');
            var nights = (end_at - start_at)/1000/60/60/24 + 1;

            var input = {
              'start_at': start_at,
              'end_at': end_at
            }
            

            $.ajax({
              url: '<%#= preview_parking_path(@parking) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @parking.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });



  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", parkings_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Reservations
      </div>
      <div class="panel-body">

        <% @parkings.each do |parking| %>
            <% parking.reservations.each do |reservation| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= reservation.start_at.strftime('%v') %>
                  </div>
                  <div class="col-md-2">
                    <%= link_to parking_path(reservation.parking) do %>
                        <%= image_tag reservation.parking.cover_photo(:thumb) %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <%= link_to reservation.parking.listing_name, parking_path(reservation.parking) %><br/><br/>
                    <span>
                      <%= link_to user_path(reservation.user) do %>
                        <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                        <%= reservation.user.fullname %>
                      <% end %>
                    </span>
                  </div>
                  <div class="col-md-3 text-right">
                    <%= render partial: "reviews/host_form", locals: {reservation: reservation} %>
                  </div>
                </div>
                <hr/>

            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", parkings_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Trips
      </div>
      <div class="panel-body">

        <% @trips.each do |trip| %>
          <div class="row">
            <div class="col-md-2">
              <%= trip.start_at.strftime('%v') %>
            </div>
            <div class="col-md-2">
              <%= link_to parking_path(trip.parking) do %>
                <%= image_tag trip.parking.cover_photo(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-5">
              <%= link_to trip.parking.listing_name, parking_path(trip.parking) %><br/><br/>
              <span>
                <%= image_tag avatar_url(trip.parking.user), class: "img-circle avatar-small" %>
                <%= link_to user_path(trip.parking.user) do %>
                    <%= trip.parking.user.fullname %>
                <% end %>
              </span>
            </div>
            <div class="col-md-3 text-right">
              <%= render partial: "reviews/guest_form", locals: {reservation: trip} %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>