config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :parkings, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'

    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'

  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :guest_reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :space_type, presence: true
  validates :area, presence: true
  validates :square_footage, presence: true
  validates :spaces, presence: true
  validates :accessibility, presence: true

  scope :recent, -> {order("parkings.updated_at DESC")}

  def cover_photo(size)
      if self.photos.length > 0
        self.photos[0].image.url(size)
      else
        "blank.jpg"
      end
    end

    def average_rating
      guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
    end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update, :destroy]


  def index
    @parkings = current_user.parkings
  end

  def new
    @parking = current_user.parkings.build
  end

  def create
    @parking = current_user.parkings.build(parking_params)
    if @parking.save
      redirect_to listing_parking_path(@parking), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
  end
end

  def show
    @photos = @parking.photos
    @guest_reviews = @parking.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
      @photos = @parking.photos
  end

  def amenities
  end

  def location
  end

  def update
    new_params = parking_params
    new_params = parking_params.merge(active: true) if is_ready_parking
    if @parking.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def destroy
  @parking.destroy
  flash[:notice] = "Successfully deleted that listing"
  redirect_to parkings_path
end

  def preload
    today = Date.today
    reservations = @parking.reservations.where("start_at >= ? OR end_at >= ?", today, today)

    render json: reservations
  end

  def preview
    start_at = Date.parse[params[:start_at]]
    end_at = Date.parse[params[:end_at]]

    output = {
      conflict: is_conflict(start_at, end_at, @parking)
    }

    render json: output
end

  private

    def is_conflict(start_at, end_at, parking)
      check = parking.reservations.where("? < start_at AND end_at < ?", start_at, end_at)
      check.size > 0? true : false
    end

    def set_parking
      @parking = Parking.find(params[:id])
    end

    def is_ready_parking
    !@parking.active && !@parking.price.blank? && !@parking.listing_name.blank? && !@parking.photos.blank? && !@parking.address.blank?
  end

    def parking_params
      params.require(:parking).permit(:space_type, :area, :square_footage, :spaces, :accessibility,
      :listing_name, :summary, :address, :is_electric, :is_water, :is_heating, :price, :active)
    end

    def is_authorized
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @parking.user_id
    end
end

app/helpers/parking_helper.rb
module ParkingHelper
end

app/views/parkings/_parking_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_parking_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_parking_path, class: "sidebar-link active" %>
    <% if !@parking.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_parking_path, class: "sidebar-link active" %>
    <% if !@parking.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_parking_path, class: "sidebar-link active" %>
    <% if !@parking.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_parking_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_parking_path, class: "sidebar-link active" %>
    <% if !@parking.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@parking.active && !@parking.price.blank? && !@parking.listing_name.blank? && !@parking.photos.blank? && !@parking.address.blank? %>

<%= form_for @parking do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>
  <div class="btn btn-form btn-small">
<%= link_to "Delete", @parking, method: :delete, data: { confirm: "Are you sure you want to delete this listing?"}, class: "btn btn-form" %>
</div>

app/views/parkings/_parkings_list.html.erb
<% @parkings.each do |parking| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= link_to (image_tag parking.cover_photo(:medium)), parking %>
        </div>
        <div class="panel-body">
          <%= link_to parking.listing_name, parking %><br/>
          $<%= parking.price %> - <%= parking.space_type %> - <%= pluralize(parking.spaces, "Space") %>
          <div id="star_<%= parking.id %>"></div> <%= pluralize(parking.average_rating, "star") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= parking.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= parking.average_rating %>
      });
    </script>
<% end %>

app/views/parkings/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @parking do |f| %>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_electric %> Electric
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_water %> Running Water
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_heating %> Heating
                </div>
              </div>
              <br/><br/>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-form" %>
              </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/parkings/create.html.erb
<h1>Parking#create</h1>
<p>Find me in app/views/parking/create.html.erb</p>

app/views/parkings/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @parking do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Summary of your parking space", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/parkings/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", parkings_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

        <% @parkings.each do |parking| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag parking.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= parking.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_parking_path(parking), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/parkings/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @parking do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Space Type</label>
                  <%= f.select :space_type, [["Garage", "Garage"], ["Driveway", "Driveway"], ["Carport", "Carport"], ["Lot", "Lot"], ["Backyard", "Backyard"]],
                                id: "space_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Parking Area</label>
                  <%= f.select :area, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                id: "area", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Square Footage</label>
                  <%= f.select :square_footage, [["150", 150], ["250", 250], ["350", 350], ["450+", 450]],
                                id: "square_footage", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Vehicle Spaces</label>
                  <%= f.select :spaces, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "spaces", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Accessibility</label>
                  <%= f.select :accessibility, [["24/7", "24/7"], ["Weekend", "Weekend"], ["Work Week", "Work Week"]],
                                id: "accessibility", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

            </div>

            <div><%= f.submit "Save", class: "btn btn-normal" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/parkings/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @parking do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Address</label>
                <%= f.text_field :address, placeholder: "What is the address?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/parkings/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your parking space!
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @parking do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Space Type</label>
              <%= f.select :space_type, [["Garage", "Garage"], ["Driveway", "Driveway"], ["Carport", "Carport"], ["Lot", "Lot"], ["Backyard", "Backyard"]],
                            id: "space_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
          <div class="form-group">
            <label>Parking Area</label>
            <%= f.select :area, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                          id: "area", prompt: "Select...", class: "form-control" %>
          </div>
        </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Square Footage</label>
              <%= f.select :square_footage, [["150", 150], ["250", 250], ["350", 350], ["450+", 450]],
                            id: "square_footage", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Vehicle Spaces</label>
              <%= f.select :spaces, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "spaces", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accessibility</label>
              <%= f.select :accessibility, [["24/7", "24/7"], ["Weekend", "Weekend"], ["Work Week", "Work Week"]],
                            id: "accessibility", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>

        <div><%= f.submit "Create My Parking Space", class: "btn btn-normal" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/parkings/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @parking, url: parking_photos_path(@parking), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/parkings/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'parking_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @parking do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Price</label>
                <%= f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/parkings/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @parking.cover_photo(nil), width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @parking.listing_name %></h1>
        <%= @parking.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@parking.user), class: "img-circle avatar-large" %><br/><br/>
        <%= @parking.user.fullname %>
      </div>
    </div>
    <hr/>

    <!-- parking Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-building fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-calculator fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-location-arrow fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-car fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @parking.space_type %></div>
        <div class="col-md-3"><%= pluralize(@parking.square_footage, "Sq Ft") %></div>
        <div class="col-md-3"><%= pluralize(@parking.area, "Parking Area") %></div>
        <div class="col-md-3"><%= pluralize(@parking.spaces, "Vehicle Space") %></div>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @parking.summary %></p>
      </div>
    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4>Amenities</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@parking.is_electric %>">Electric</li>
              <li class="<%= 'text-line-through' if !@parking.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@parking.is_water %>">Running Water</li>
            </ul>
          </div>


        </div>
      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@guest_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBskFfa97x9qlsGemgLp_SHIH7rkbYJau0"></script>
      <script>
          function initialize() {
            var location = {lat: <%= @parking.latitude %>, lng: <%= @parking.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              center: location,
              zoom: 14
            });

            var marker = new google.maps.Marker({
              position: location,
              map: map
            });

            var infoWindow = new google.maps.InfoWindow({
              content: '<div id="content"><%= image_tag @parking.cover_photo(:medium) %></div>'
            });

            infoWindow.open(map, marker);
          }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>



    <!-- NEAR BY parking -->
    <div class="row">
      <h3>Near by</h3>
      <% for parking in @parking.nearbys(10) %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading preview">
                <%= image_tag parking.cover_photo(:medium) %>
              </div>
              <div class="panel-body">
                <%= link_to parking.listing_name, parking %><br/>
                (<%= parking.distance.round(2) %> miles away)
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>



  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

<script>
$('#average_rating').raty({
  path: '/assets',
  readOnly: true,
  score: <%= @parking.average_rating %>
});
</script>

app/views/parkings/update.html.erb
<h1>Parking#update</h1>
<p>Find me in app/views/parking/update.html.erb</p>